services:
  personaplex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8998:8998"
    environment:
      - NO_TORCH_COMPILE=1
    env_file:
      - .env
    command: ["/app/moshi/.venv/bin/python", "-m", "moshi.server", "--ssl", "/app/ssl", "--cpu-offload", "--host", "0.0.0.0"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./.cache:/root/.cache
