services:
  personaplex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8998:8998"
    environment:
      - NO_TORCH_COMPILE=1
      - TORCH_COMPILE_DISABLE=1
      - TORCHINDUCTOR_MAX_AUTOTUNE=0
      - TORCHINDUCTOR_COMPILE_THREADS=1
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    env_file:
      - .env
    command: ["/app/moshi/.venv/bin/python", "-m", "moshi.server", "--ssl", "/app/ssl", "--host", "0.0.0.0", "--lowvram"]
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./.cache:/root/.cache
